[package]
name = "player-lyrics"
version = "0.1.0"
edition = "2021"
authors = ["Laurent Brock <laurentbrock@live.com.au>"]

[dependencies]
mpris = "2.0.1"
reqwest = {version = "0.12.5", features = ["blocking"]}
scraper = "0.19.0"
